
# 03 — Perform a train test split

A goal of machine learning is to build a model that performs well on new data.  
The problem is that you might not have new data available.

In this notebook, you’ll learn how to simulate unseen data by splitting what you already have into training and testing sets.

## Imports

In [5]:

import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split

## Load the Titanic dataset

In [3]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## Select features and target

In [4]:
X = titanic[["pclass", "sex", "age"]]
y = titanic["survived"]

X,y

(     pclass     sex   age
 0         3    male  22.0
 1         1  female  38.0
 2         3  female  26.0
 3         1  female  35.0
 4         3    male  35.0
 ..      ...     ...   ...
 886       2    male  27.0
 887       1  female  19.0
 888       3  female   NaN
 889       1    male  26.0
 890       3    male  32.0

 [891 rows x 3 columns],
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: survived, Length: 891, dtype: int64)

## Perform the train-test split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.head(5)
# X_train.shape, X_test.shape, y_train.shape, y_test.shape

     pclass     sex   age
165       3    male   9.0
541       3  female   9.0
625       1    male  61.0
388       3    male   NaN
76        3    male   NaN